Added post semantics in html
Diptenusarkar/html.org.in pull request #106
Opened 2023-10-07 08:11 UTC by maida12

2023-10-07 08:43 UTC, Diptenusarkar requested changes
Need to comply with this code example.

2023-10-07 08:43 UTC, Diptenusarkar commented on index.html
> +                        <a href="/html/html_math/">Learn More <i class="bi bi-book"></i></a>
``` suggestion
                        <a href="/html/html_semantics/">Learn More <i class="bi bi-book"></i></a>
```

2023-10-07 08:43 UTC, Diptenusarkar commented on html/html_semantics/index.html
> +            <a href="#"><i class="bi bi-chevron-double-left"></i> Previous</a>
```suggestion
            <a href="../html_math/"><i class="bi bi-chevron-double-left"></i> Previous</a>
```

2023-10-07 08:43 UTC, Diptenusarkar commented on html/html_semantics/index.html
> +            <a href="#">Next <i class="bi bi-chevron-double-right"></i></a>
```suggestion
            <a href="/">Next <i class="bi bi-chevron-double-right"></i></a>
```

2023-10-07 08:43 UTC, Diptenusarkar commented on html/html_semantics/index.html
> +            <a href="#"><i class="bi bi-chevron-double-left"></i> Previous</a>
``` suggestion
            <a href="../html_math/"><i class="bi bi-chevron-double-left"></i> Previous</a>
```

2023-10-07 08:43 UTC, Diptenusarkar commented on html/html_semantics/index.html
> +            <a href="#">Next <i class="bi bi-chevron-double-right"></i></a>
```suggestion
            <a href="/">Next <i class="bi bi-chevron-double-right"></i></a>
```

2023-10-09 05:03 UTC, maida12 commented
I did all these changes

2023-10-09 12:52 UTC, Diptenusarkar commented
something is not working

2023-10-10 04:21 UTC, maida12 commented
should i make a new pull request?

2023-10-12 16:04 UTC, closed without merging