added the html_graphics Tag
Diptenusarkar/html.org.in pull request #60
Opened 2022-10-17 12:26 UTC by theanimator20

Hello @Diptenusarkar ,

i have done the work assigned to me please consider merging the PR

Thank You !!
![hop](https://user-images.githubusercontent.com/97297724/196176742-901f7886-3b78-4192-a57a-b753db41bdc3.PNG)

2022-10-17 12:31 UTC, theanimator20 commented
@Diptenusarkar  Once verified do accept my PR with an hacktoberfest label
Happy Coding !!

2022-10-17 12:38 UTC, Diptenusarkar approved these changes

2022-10-17 12:39 UTC, Diptenusarkar commented
Remove Conflicting

2022-10-17 12:53 UTC, theanimator20 commented
> Remove Conflicting

✅

2022-10-17 18:23 UTC, theanimator20 commented
@Diptenusarkar  shall i close the pull request?? Or u will do it

2022-10-17 23:27 UTC, Diptenusarkar commented on html/html_forms/index.html
> +            <a href="../html_colors/"><i class="bi bi-chevron-double-left"></i> Previous</a>
Why add extra button

2022-10-17 23:31 UTC, Diptenusarkar requested changes
Fix all problem 
![Screenshot (1213)](https://user-images.githubusercontent.com/50952901/196302301-8974a5b5-2bd4-4a9d-84c6-1b4577e900d0.png)
![Screenshot (1212)](https://user-images.githubusercontent.com/50952901/196302315-4ce3c8fe-1623-45c7-aac8-efc7049d8dfa.png)
![Screenshot (1211)](https://user-images.githubusercontent.com/50952901/196302333-5b8a7301-5add-4813-afcb-2af86b8e32df.png)

2022-10-18 04:39 UTC, theanimator20 commented
Okk

2022-10-18 05:51 UTC, theanimator20 commented
@Diptenusarkar  solved the requested changes

2022-10-18 06:17 UTC, theanimator20 commented
Done  ✅ ✅

2022-10-18 06:58 UTC, Diptenusarkar commented
Please Check link Page.

2022-10-18 07:13 UTC, theanimator20 commented
> Please Check link Page.

What's the issue with link page it's working fine right?

2022-10-18 07:25 UTC, Diptenusarkar commented
![Screenshot (1214)](https://user-images.githubusercontent.com/50952901/196364106-183ff7aa-086a-48c2-ac08-57b0b754b640.png)

2022-10-18 08:00 UTC, theanimator20 commented
@Diptenusarkar  i have resolved the issues kindly go through it

2022-10-18 10:15 UTC, Diptenusarkar commented
Good Job 👍

2022-10-18 10:16 UTC, merged